version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nohax
      POSTGRES_PASSWORD: hackmebitch!
      POSTGRES_DB: nohaxdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  postgres_data:
