version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    devices:
      - "/dev/cu.usbmodem2101:/dev/cu.usbmodem2101"
    environment:
      - DATABASE_URL=postgresql://nohax:hackmebitch!@postgres:5432/nohaxdb
    depends_on:
      - postgres
    command: sh -c "python create_tables.py && uvicorn main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: nohax
      POSTGRES_PASSWORD: hackmebitch!
      POSTGRES_DB: nohaxdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
